[package]
name = "telamon-cli"
version = "0.1.0"
authors = ["Basile Clement <basile.clement@ens.fr>"]

[dependencies]
env_logger = "0.5.9"
structopt = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
toml = "0.4"
log = "0.4.1"
num_cpus = "1.8.0"
telamon = { path = "../" }
