[package]
authors = ["Basile Clement <basile.clement@ens.fr>"]
name = "cudnn"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
cuda-sys = { path = "../cuda-sys", features = ["cudnn"] }
